server:
  port: 8087
  servlet:
    context-path: /

# Swagger UI 配置
mconfig:
  swagger-ui-open: true

user:
  name: jerry

swagger:
  base-package: com.example.demo.controller

mybatis:
  mapper-locations: classpath*:com/trinasolar/csde/after/sale/api/mapper/*-Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
oauth2:
  ignore-path: /api/**,/demo/**,/loginByTx,/loginByTft,/dict/refresh